name: Create Production Builds

on:
  push:
    branches:
      - production/mobile

jobs:
  build_android:
    name: Build Android AAB
    type: build
    params:
      platform: android

  submit_android:
    name: Submit Android to Google Play
    needs: [build_android]
    type: submit
    params:
      platform: android
      build_id: ${{ needs.build_android.output.build_id }}

  build_ios:
    name: Build iOS IPA
    type: build
    params:
      platform: ios

  submit_ios:
    name: Submit iOS to App Store
    needs: [build_ios]
    type: submit
    params:
      platform: ios
      build_id: ${{ needs.build_ios.output.build_id }}
