name: Create Production Builds

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android AAB
    type: build
    params:
      platform: android

  build_ios:
    name: Build iOS IPA
    type: build
    params:
      platform: ios
