"""add_raw_pricing_text_to_scraped_events

Revision ID: 9e1fc8d7fde2
Revises: a1b2c3d4e5f6
Create Date: 2026-03-21 21:13:14.536224
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9e1fc8d7fde2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_events', sa.Column('raw_pricing_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_events', 'raw_pricing_text')
    # ### end Alembic commands ###
