import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { PageContainer } from "@/components/page-container";

interface AcessibilidadePageProps {
  readonly params: Promise<{ readonly locale: string }>;
}

export async function generateMetadata({
  params,
}: AcessibilidadePageProps): Promise<Metadata> {
  const { locale } = await params;

  return {
    title: "Declaração de Acessibilidade e Usabilidade | Athlifyr",
    description:
      "Declaração de Acessibilidade e Usabilidade do sítio web Athlifyr, conforme o Decreto-Lei n.º 83/2018, de 19 de outubro.",
    alternates: {
      canonical: `https://www.athlifyr.com/${locale}/acessibilidade`,
    },
  };
}

/**
 * Official Accessibility and Usability Declaration page.
 *
 * This page hosts the HTML generated by the Portuguese government's
 * "Gerador da Declaração de Acessibilidade e Usabilidade"
 * (https://www.acessibilidade.gov.pt/gerador/).
 *
 * Required by DL n.º 83/2018 to be published at /acessibilidade/.
 * The generator outputs structured HTML — do NOT alter the structure.
 */
export default async function AcessibilidadePage({
  params,
}: AcessibilidadePageProps) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <PageContainer size="lg" maxWidth="max-w-4xl">
      <article className="prose prose-gray dark:prose-invert max-w-none">
        {/* ====================================================================
         *  DECLARAÇÃO DE ACESSIBILIDADE E USABILIDADE
         *  ==================================================================
         *
         *  INSTRUÇÕES:
         *  1. Vai ao Gerador: https://www.acessibilidade.gov.pt/gerador/
         *  2. Preenche o formulário (ver guia de preenchimento abaixo)
         *  3. No final, clica em "Descarregar HTML"
         *  4. Cola o conteúdo HTML gerado AQUI, substituindo este placeholder
         *
         *  IMPORTANTE: Não alteres a estrutura do HTML gerado pelo Gerador.
         *  O documento é construído para ser lido por máquinas.
         *  ==================================================================
         */}

        <h1>Declaração de Acessibilidade e Usabilidade</h1>

        <p>
          <strong>Estado:</strong> Esta página irá conter a Declaração de
          Acessibilidade e Usabilidade oficial, gerada através do{" "}
          <a
            href="https://www.acessibilidade.gov.pt/gerador/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Gerador da Declaração de Acessibilidade e Usabilidade
          </a>{" "}
          conforme o Decreto-Lei n.º 83/2018, de 19 de outubro.
        </p>

        <p>
          Para mais informações sobre as funcionalidades de acessibilidade
          atuais do Athlifyr, consulte a nossa{" "}
          <a href={`/${locale}/accessibility`}>página de acessibilidade</a>.
        </p>

        <div className="mt-8 rounded-lg border border-amber-500/30 bg-amber-500/10 p-6">
          <p className="mb-0 text-sm text-amber-700 dark:text-amber-400">
            A Declaração oficial está em preparação e será publicada nesta
            página brevemente.
          </p>
        </div>
      </article>
    </PageContainer>
  );
}
